version: '2.1'

services:
  hae-mongo:
    container_name: hae-mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - hae_network
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}


  hae-grafana:
    container_name: hae-grafana
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - hae_network
    user: "0:0" # you may need to uncomment this line if using Ubuntu or if you expereince permission errors
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=yesoreyeram-infinity-datasource
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasourc
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  hae-server:
    container_name: hae-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - READ_TOKEN=${READ_TOKEN}
      - WRITE_TOKEN=${WRITE_TOKEN}

    depends_on:
      - hae-mongo
    networks:
      - hae_network
    restart: unless-stopped

networks:
  hae_network:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data:
  grafana_data: {}
